### ISSUE TITLE
Infinite loop in program

### ISSUE THREAD

**Issue by Martinfx** [Martinfx/Cobol#3]
Infinite loop in program loop.cbl. Maybe missing database file.
Cobol/OpenCobol/Loops/loop.cbl

**Comment by Malanius** [comment]
It should not even compile as there is an error in the file definition.
```
ORGANIZATION IS SEQUENTIAL
ACCESS IS RANDOM
```
There can't be mixed SEQUENTIAL, for SEQUENTIAL organised files, access should be SEQUENTIAL too.
RANDOM access is for INDEX organisation.

Also, at the reading loop, there is missing NEXT statement, so it always reads the same record, causing the infinite loop.

**Comment by Martinfx** [comment]
Thank you !
