### ISSUE TITLE
Use whole source with line time stamps and numbers for AS/400 sources

### ISSUE THREAD

**Issue by Malanius** [Martinfx/Cobol#6]
As some says, it can't be used directly. That's true as the source codes were copied from RAD for i.

**Comment by Martinfx** [comment]
Yes, this is good idea.

**Comment by Malanius** [comment]
So, I've taken a look into this. The sources for the AS/400 part are accurate as they are, as all of them has the correct whitespace offset to accommodate the additional info.
When the sources are downloaded with FTP, it is without this additional info and can be uploaded without it as well - SEU and compiler will handle it just well.
It seems that RADi is actually taking a different approach to download the sources - most probably JDBC, as if SQL is used on SRC-PF, it returns the sequence and date fields as well.
And as RADi is not free, it will be better not to go this way. I will prepare a manual on how to deal with sources via FTP.
