### ISSUE TITLE
core_basic_window cannot be compiled with latest raylib

### ISSUE THREAD

**Issue by rainbof** [Martinfx/Cobol#7]
this part of code 

```
CALL STATIC "DrawText" USING
* FIXME: This a part is ungly (RAN-NUM)
BY VALUE RAN-NUM
BY VALUE 360 180
BY VALUE 80
BY CONTENT W-COLOR-LIGHTGRAY
RETURNING OMITTED
END-CALL
```
cause error:

> core_basic_window.cbl: 116: attempt to reference unallocated memory (signal SIGSEGV)
> abnormal termination - file contents may be incorrect

because RAN-NUM is binnary type.

my solution is attached :)
[core_basic_window.txt](https://github.com/Martinfx/Cobol/files/2261493/core_basic_window.txt)

**Comment by Martinfx** [comment]
Fixed in commit https://github.com/Martinfx/Cobol/commit/7aec45922a57253b4a165f910885611bc07a9e0a
